#!/usr/bin/env python3
"""Generate bundled profession trainer fees for the pinned Forever client (stdlib only)."""

import argparse
import csv
import io
from collections import Counter, defaultdict
import gzip
import re
import sys
import urllib.error
import urllib.request

from gen_recipes import threshold_ids
from gen_thresholds import BUILD, CACHE, ROOT, download

OUTPUT = ROOT / "Data" / "Trainer.lua"
CLASSICDB_COMMIT = "22b51464f1625f6ef6275771de1f5466c6f5d19e"
CLASSICDB_URL = (
    "https://raw.githubusercontent.com/cmangos/classic-db/"
    f"{CLASSICDB_COMMIT}/Full_DB/ClassicDB_1_12_1_z2815.sql.gz"
)
CLASSICDB_CACHE = CACHE / f"classicdb-{CLASSICDB_COMMIT[:7]}.sql.gz"
PROFESSION_SKILLS = {129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393}
LEARN_SPELL = 36
# Forever's client leaves out the trainers' teaching spells; Classic Era keeps them,
# with the same recipe spell IDs.
TEACH_BUILD = "1.15.9.69722"
# entry, spell, spellcost, reqskill, reqskillvalue, reqlevel, ReqAbility1-3, condition_id
ROW = re.compile(r"\((\d+),(\d+),(\d+),(\d+),(\d+),(\d+),(NULL|\d+),(NULL|\d+),(NULL|\d+),(\d+)\)")


def classicdb(refresh=False, offline=False):
    if not CLASSICDB_CACHE.exists() or refresh:
        if offline:
            raise ValueError(f"Missing cached source: {CLASSICDB_CACHE}")
        request = urllib.request.Request(CLASSICDB_URL, headers={"User-Agent": "SkillUpForever/1.0"})
        with urllib.request.urlopen(request, timeout=120) as response:
            data = response.read()
        temporary = CLASSICDB_CACHE.with_suffix(".tmp")
        CACHE.mkdir(parents=True, exist_ok=True)
        temporary.write_bytes(data)
        temporary.replace(CLASSICDB_CACHE)
    with gzip.open(CLASSICDB_CACHE, "rt", encoding="utf-8", errors="replace") as dump:
        return [line for line in dump if line.startswith("INSERT INTO `npc_trainer` VALUES")]


def teach_effects(refresh=False, offline=False):
    content = download(
        f"https://wago.tools/db2/SpellEffect/csv?build={TEACH_BUILD}",
        f"SpellEffect-{TEACH_BUILD}.csv", refresh, offline,
    )
    rows = list(csv.DictReader(io.StringIO(content)))
    if not rows or not {"SpellID", "DifficultyID", "Effect", "EffectTriggerSpell"} <= rows[0].keys():
        raise ValueError(f"SpellEffect {TEACH_BUILD}: empty or missing columns")
    return rows


def generate(ids, trainer_lines, effect_rows):
    teaches = defaultdict(set)
    for row in effect_rows:
        if int(row["Effect"]) == LEARN_SPELL and int(row["DifficultyID"]) == 0:
            teaches[int(row["SpellID"])].add(int(row["EffectTriggerSpell"]))
    # Specialisation-gated rows (condition, required ability) can't be assumed
    # trainable; a recipe offered without a gate anywhere is.
    fees = defaultdict(Counter)
    for line in trainer_lines:
        for match in ROW.finditer(line):
            _, spell, cost, skill, required, _, ability, _, _, condition = match.groups()
            if int(skill) not in PROFESSION_SKILLS or ability != "NULL" or condition != "0":
                continue
            for recipe in teaches.get(int(spell), ()):
                if recipe in ids:
                    fees[recipe][(int(cost), int(required))] += 1
    if not fees:
        raise ValueError("No trainer fees resolved; leaving existing output untouched")
    # Duplicate trainers almost always agree; take the most common (fee, skill), cheaper on a tie.
    chosen = {recipe: min(c.items(), key=lambda kv: (-kv[1], kv[0]))[0] for recipe, c in fees.items()}
    conflicts = sorted(recipe for recipe, c in fees.items() if len(c) > 1)
    return chosen, conflicts


def render(fees, conflicts):
    lines = [
        "-- Generated by tools/gen_trainer.py — do not edit.",
        f"-- Source: CMaNGOS classic-db {CLASSICDB_COMMIT} npc_trainer (GPL-3.0), base fees before",
        "-- reputation discounts; teaching spell -> recipe via wago.tools SpellEffect (LEARN_SPELL),",
        f"-- wow_classic_era {TEACH_BUILD}; recipes limited to wow_classic_beta {BUILD} thresholds.",
        "-- Specialisation-gated rows are left out. Fees seen at a trainer win.",
        f"-- recipes={len(fees)}; conflicts resolved to the most common: {conflicts}.",
        "local _, ns = ...",
        "-- stylua: ignore",
        "-- [recipeID] = { fee in copper, required base skill }",
        "ns.TrainerFees = {",
    ]
    lines.extend(f"\t[{recipe}] = {{ {fee}, {skill} }}," for recipe, (fee, skill) in sorted(fees.items()))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="redownload the pinned sources")
    mode.add_argument("--offline", action="store_true", help="use cached sources only")
    args = parser.parse_args()
    options = {"refresh": args.refresh, "offline": args.offline}
    fees, conflicts = generate(
        threshold_ids(),
        classicdb(**options),
        teach_effects(**options),
    )
    content = render(fees, conflicts)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}: {len(fees)} recipes, conflicts {conflicts}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
