#!/usr/bin/env python3
"""Generate vendor prices for trade reagents from the pinned Forever client (stdlib only)."""

import argparse
import re
import sys

from gen_thresholds import BUILD, ROOT, SOURCE_DATE, db2, download

# Which items vendors sell is server data the client doesn't ship, so the list
# comes from LibPeriodicTable; the prices come from this build's ItemSparse.
PT_COMMIT = "130c6a9f73671f4ba80d17caa95f2f4cf3dbf81c"
PT_URL = (
    "https://raw.githubusercontent.com/doadin/libperiodictable-3-1/"
    f"{PT_COMMIT}/LibPeriodicTable-3.1-Tradeskill/LibPeriodicTable-3.1-Tradeskill.lua"
)
PT_SET = re.compile(r'\["Tradeskill\.Mat\.BySource\.Vendor"\]="([^"]*)"')
OUTPUT = ROOT / "Data" / "Vendor.lua"


def vendor_items(content):
    match = PT_SET.search(content)
    if not match:
        raise ValueError("LibPeriodicTable: Tradeskill.Mat.BySource.Vendor set not found")
    return sorted({int(entry.split(":")[0]) for entry in match[1].split(",") if entry})


def render(prices):
    lines = [
        "-- Generated by tools/gen_vendor.py; do not edit.",
        f"-- Items: LibPeriodicTable-3.1 Tradeskill.Mat.BySource.Vendor @ {PT_COMMIT[:12]} (LGPL-2.1).",
        f"-- Prices: wago.tools ItemSparse BuyPrice / VendorStackCount, wow_classic_beta {BUILD}, {SOURCE_DATE}.",
        "local _, ns = ...",
        "",
        "-- [itemID] = copper per unit",
        "ns.VendorPrices = {",
    ]
    for item_id, name, copper in prices:
        value = int(copper) if copper == int(copper) else copper
        lines.append(f"\t[{item_id}] = {value}, -- {name}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="redownload the pinned sources")
    mode.add_argument("--offline", action="store_true", help="use cached sources only")
    args = parser.parse_args()

    listed = vendor_items(download(PT_URL, f"PT-Tradeskill-{PT_COMMIT}.lua", args.refresh, args.offline))
    items = {
        int(row["ID"]): row
        for row in db2("ItemSparse", ["ID", "Display_lang", "BuyPrice", "VendorStackCount"], args.refresh, args.offline)
    }
    prices, absent = [], []
    for item_id in listed:
        row = items.get(item_id)
        if not row or int(row["BuyPrice"]) <= 0:
            absent.append(item_id)
            continue
        per_unit = int(row["BuyPrice"]) / max(int(row["VendorStackCount"]), 1)
        prices.append((item_id, row["Display_lang"], per_unit))
    OUTPUT.write_text(render(prices), encoding="utf-8")
    print(f"{len(prices)} vendor reagents written; {len(absent)} listed items not sold in {BUILD}: {absent}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
